tasks:
  aws-cli:
    name: "AWS CLI Install"
    description: "Installs the AWS CLI"
    command: |
      cd /workspaces
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
    triggeredBy:
      - postEnvironmentStart
  react-js:
    name: "NPM install"
    command: |
      cd frontend-react-js
      npm i
    triggeredBy:
      - postEnvironmentStart

